version: '3'
services:
  todoback:
    image: todobackend
    restart: always
    ports: 
      - 3001:3001

  todofront:
    depends_on:
      - todoback
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback

  todotests:
    image: todotests
    restart: always
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront